MedicinskiSustav/Controllers/PreglediController.cs
using AutoMapper;
using MedicinskiSustav.Models;
using MedicinskiSustav.Repositories;
using MedicinskiSustav.Viewmodels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MedicinskiSustav.Controllers
{
    public class PreglediController : Controller
    {
        private readonly IRepositoryFactory _repositoryFactory;
        private readonly IMapper _mapper;

        public PreglediController(IRepositoryFactory repositoryFactory, IMapper mapper)
        {
            _repositoryFactory = repositoryFactory;
            _mapper = mapper;
        }

        // GET: PreglediController
        public async Task<IActionResult> Index()
        {
            var repo = _repositoryFactory.GetRepository<Pregled>();
            var pregledi = await repo.GetAll().ToListAsync();

            var vm = _mapper.Map<IEnumerable<PregledVM>>(pregledi);
            return View(vm);
        }

        // GET: PreglediController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var repo = _repositoryFactory.GetRepository<Pregled>();
            var pregled = await repo.GetByIdAsync(id);

            if (pregled == null)
            {
                return NotFound();
            }

            var vm = _mapper.Map<PregledDetailsVM>(pregled);
            return View(vm);
        }

        // GET: PreglediController/Create
        public IActionResult Create(int pacijentId)
        {
            var vm = new PregledCreateVM
            {
                PacijentId = pacijentId,
                VrijemePregleda = DateTime.Now
            };

            ViewBag.SifrePregleda = Enum.GetValues(typeof(SifraPregleda));
            return View(vm);
        }

        // POST: PreglediController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PregledCreateVM pregledCreateVM)
        {
            if (ModelState.IsValid)
            {
                var repo = _repositoryFactory.GetRepository<Pregled>();
                var pregled = _mapper.Map<Pregled>(pregledCreateVM);

                await repo.InsertAsync(pregled);
                await repo.SaveAsync();

                TempData["Success"] = "Pregled uspješno kreiran!";
                return RedirectToAction(nameof(Index));
            }

            ViewBag.SifrePregleda = Enum.GetValues(typeof(SifraPregleda));
            return View(pregledCreateVM);
        }

        // GET: PreglediController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var repo = _repositoryFactory.GetRepository<Pregled>();
            var pregled = await repo.GetByIdAsync(id);

            if (pregled == null)
            {
                return NotFound();
            }

            var vm = _mapper.Map<PregledEditVM>(pregled);
            ViewBag.SifrePregleda = Enum.GetValues(typeof(SifraPregleda));
            return View(vm);
        }

        // POST: PreglediController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, PregledEditVM pregledEditVM)
        {
            if (id != pregledEditVM.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var repo = _repositoryFactory.GetRepository<Pregled>();
                var pregled = await repo.GetByIdAsync(id);

                if (pregled == null)
                {
                    return NotFound();
                }

                _mapper.Map(pregledEditVM, pregled);
                await repo.UpdateAsync(pregled);
                await repo.SaveAsync();

                TempData["Success"] = "Pregled uspješno ažuriran!";
                return RedirectToAction("Details", new { id });
            }

            ViewBag.SifrePregleda = Enum.GetValues(typeof(SifraPregleda));
            return View(pregledEditVM);
        }

        // POST: PreglediController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var repo = _repositoryFactory.GetRepository<Pregled>();
            
            await repo.DeleteAsync(id);
            await repo.SaveAsync();

            TempData["Success"] = "Pregled uspješno obrisan!";
            return RedirectToAction(nameof(Index));
        }
    }
}

MedicinskiSustav/Controllers/ReceptiController.cs
using AutoMapper;
using MedicinskiSustav.Models;
using MedicinskiSustav.Repositories;
using MedicinskiSustav.Viewmodels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MedicinskiSustav.Controllers
{
    public class ReceptiController : Controller
    {
        private readonly IRepositoryFactory _repositoryFactory;
        private readonly IMapper _mapper;

        public ReceptiController(IRepositoryFactory repositoryFactory, IMapper mapper)
        {
            _repositoryFactory = repositoryFactory;
            _mapper = mapper;
        }

        // GET: ReceptiController/Create
        public IActionResult Create(int pregledId)
        {
            var lijekoviRepo = _repositoryFactory.GetRepository<Lijek>();
            var lijekovi = lijekoviRepo.GetAll();

            ViewBag.Lijekovi = new SelectList(lijekovi, "Id", "Naziv");    

            var vm = new ReceptCreateVM { PregledId = pregledId };
            return View(vm);
        }

        // POST: ReceptiController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ReceptCreateVM receptCreateVM)
        {
            if (ModelState.IsValid)
            {
                var recept = _mapper.Map<Recept>(receptCreateVM);
                var repo = _repositoryFactory.GetRepository<Recept>();

                await repo.InsertAsync(recept);
                await repo.SaveAsync();

                TempData["Success"] = "Recept uspješno dodan!";
                return RedirectToAction("Details", "Pregledi", new { id = receptCreateVM.PregledId });
            }

            var lijekoviRepo = _repositoryFactory.GetRepository<Lijek>();
            var lijekovi = lijekoviRepo.GetAll();
            ViewBag.Lijekovi = new SelectList(lijekovi, "Id", "Naziv", receptCreateVM.LijekId);

            return View(receptCreateVM);
        }

        // GET: ReceptiController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var repo = _repositoryFactory.GetRepository<Recept>();
            var recept = await repo.GetByIdAsync(id);

            if (recept == null)
            {
                return NotFound();
            }

            var lijekoviRepo = _repositoryFactory.GetRepository<Lijek>();
            var lijekovi = lijekoviRepo.GetAll();

            ViewBag.Lijekovi = new SelectList(lijekovi, "Id", "Naziv", recept.LijekId);

            var vm = _mapper.Map<ReceptEditVM>(recept);
            return View(vm);
        }

        // POST: ReceptiController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ReceptEditVM receptEditVM)
        {
            if (id != receptEditVM.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var repo = _repositoryFactory.GetRepository<Recept>();
                var recept = await repo.GetByIdAsync(id);

                if (recept == null)
                {
                    return NotFound();
                }

                _mapper.Map(receptEditVM, recept);

                await repo.UpdateAsync(recept);
                await repo.SaveAsync();

                TempData["Success"] = "Recept je uspješno ažuriran!";
                return RedirectToAction("Details", "Pregledi", new { id = recept.PregledId });
            }
            return View(receptEditVM);
        }

        // POST: ReceptiController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var repo = _repositoryFactory.GetRepository<Recept>();
            var recept = await repo.GetByIdAsync(id);
            
            await repo.DeleteAsync(id);
            await repo.SaveAsync();

            return RedirectToAction("Details", "Pregledi", new { id = recept.PregledId });
        }
    }
}

MedicinskiSustav/Controllers/SlikeController.cs
using AutoMapper;
using MedicinskiSustav.Models;
using MedicinskiSustav.Repositories;
using MedicinskiSustav.Viewmodels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Minio;
using Minio.DataModel.Args;
using System.Linq;

namespace MedicinskiSustav.Controllers
{
    public class SlikeController : Controller
    {
        private readonly IRepositoryFactory _repositoryFactory;
        private readonly IMapper _mapper;
        private readonly IMinioClient _minio;
        private readonly string _bucket;

        public SlikeController(IRepositoryFactory repositoryFactory, IMapper mapper, IMinioClient minio, IConfiguration config)
        {
            _repositoryFactory = repositoryFactory;
            _mapper = mapper;
            _minio = minio;
            _bucket = config["Minio:Bucket"] ?? "slike";
        }

        // GET: SlikeController/Create
        public IActionResult Create(int pregledId)
        {
            SlikaCreateVM vm = new() { PregledId = pregledId };

            return View(vm);
        }

        // POST: SlikeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SlikaCreateVM slikaCreateVM)
        {
            if (ModelState.IsValid && slikaCreateVM.Slika != null)
            {
                var allowedExtensions = new[] { ".jpg", ".jpeg", ".png", ".gif" };
                var fileExtension = Path.GetExtension(slikaCreateVM.Slika.FileName).ToLower();

                if (!allowedExtensions.Contains(fileExtension))
                {
                    ModelState.AddModelError("Slika", "Dozvoljeni formati: JPG, PNG, GIF");
                    return View(slikaCreateVM);
                }

                var uniqueFileName = $"{Guid.NewGuid()}-{slikaCreateVM.Slika.FileName}";
                var beArgs = new BucketExistsArgs().WithBucket(_bucket);
                bool found = await _minio.BucketExistsAsync(beArgs);

                if (!found)
                {
                    var mbArgs = new MakeBucketArgs().WithBucket(_bucket);
                    await _minio.MakeBucketAsync(mbArgs);
                }

                using (var stream = slikaCreateVM.Slika.OpenReadStream())
                {
                    var putObjectArgs = new PutObjectArgs()
                        .WithBucket(_bucket)
                        .WithObject(uniqueFileName)
                        .WithStreamData(stream)
                        .WithObjectSize(stream.Length)
                        .WithContentType(slikaCreateVM.Slika.ContentType);

                    await _minio.PutObjectAsync(putObjectArgs);
                }

                Slika slika = new()
                {
                    Putanja = uniqueFileName,
                    PregledId = slikaCreateVM.PregledId
                };

                var repo = _repositoryFactory.GetRepository<Slika>();
                await repo.InsertAsync(slika);
                await repo.SaveAsync();

                TempData["Success"] = "Slika uspješno dodana!";
                return RedirectToAction("Details", "Pregledi", new { id = slikaCreateVM.PregledId });
            }

            return View(slikaCreateVM);
        }

        // POST: SlikeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var repo = _repositoryFactory.GetRepository<Slika>();
            var slika = await repo.GetByIdAsync(id);

            if (slika == null)
            {
                return NotFound();
            }

            var removeObjectArgs = new RemoveObjectArgs()
                 .WithBucket(_bucket)
                 .WithObject(slika.Putanja);

            await _minio.RemoveObjectAsync(removeObjectArgs);

            await repo.DeleteAsync(id);
            await repo.SaveAsync();

            TempData["Success"] = "Slika uspješno obrisana!";
            return RedirectToAction("Details", "Pregledi", new { id = slika.PregledId });
        }
    }
}

MedicinskiSustav/Views/Pregledi/Create.cshtml
@model MedicinskiSustav.Viewmodels.PregledCreateVM

<h2>Novi pregled</h2>

<form asp-action="Create">
    <input type="hidden" asp-for="PacijentId" />

    <div class="form-group mb-3">
        <label asp-for="SifraPregleda"></label>
        <select asp-for="SifraPregleda"
                asp-items="Html.GetEnumSelectList<SifraPregleda>()"
                class="form-select">
            <option value="">Odaberite šifru</option>
        </select>
        <span asp-validation-for="SifraPregleda" class="text-danger"></span>
    </div>

    <div class="form-group mb-3">
        <label asp-for="VrijemePregleda"></label>
        <input asp-for="VrijemePregleda" type="datetime-local" value="@(Model.VrijemePregleda.ToString("yyyy-MM-ddTHH:mm"))" class="form-control" />
        <span asp-validation-for="VrijemePregleda" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">
        <i class="fas fa-save"></i> Kreiraj pregled
    </button>
</form>

MedicinskiSustav/Views/Pregledi/Details.cshtml
@model MedicinskiSustav.Viewmodels.PregledDetailsVM

<div class="container">
    <h2>Detalji pregleda</h2>

    <div class="card mb-4">
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-3">Šifra pregleda:</dt>
                <dd class="col-sm-9">@Model.SifraPregleda</dd>

                <dt class="col-sm-3">Vrijeme pregleda:</dt>
                <dd class="col-sm-9">@Model.VrijemePregleda.ToString("dd.MM.yyyy")</dd>

                <dt class="col-sm-3">Pacijent:</dt>
                <dd class="col-sm-9">@Model.PacijentImePrezime</dd>
            </dl>
        </div>
    </div>

    <h3>Recepti</h3>

    @if (Model.Recepti?.Any() == true)
    {
        <ul class="list-group">
            @foreach (var recept in Model.Recepti)
            {
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <span>
                        <i class="fas fa-prescription me-2"></i> @recept.LijekNaziv
                    </span>
                    <span>
                        <a asp-controller="Recepti" asp-action="Edit" asp-route-id="@recept.Id" class="btn btn-warning btn-sm me-1">
                            <i class="fas fa-edit"></i>
                        </a>
                        <form asp-controller="Recepti" asp-action="Delete" method="post" style="display:inline">
                            <input type="hidden" name="id" value="@recept.Id" />
                            @Html.AntiForgeryToken()
                            <button type="button" class="btn btn-danger btn-sm" onclick="confirmDelete(this)">
                                <i class="fas fa-trash"></i>
                            </button>
                        </form>
                    </span>
                </li>
            }
        </ul>
    }
    else
    {
        <p class="text-muted">Nema izdanih recepata</p>
    }
    <a asp-controller="Recepti" asp-action="Create" asp-route-pregledId="@Model.Id" class="btn btn-success mb-3">
        <i class="fas fa-plus"></i> Novi recept
    </a>
    <div class="card mt-4">
        <div class="card-header bg-primary text-white d-flex justify-content-between align-items-center">
            <h3 class="card-title mb-0">Slike</h3>
            <a asp-controller="Slike" asp-action="Create" asp-route-pregledId="@Model.Id" class="btn btn-success btn-sm">
                <i class="fas fa-plus"></i> Nova slika
            </a>
        </div>
        <div class="card-body">
            @if (Model.Slike?.Any() == true)
            {
                <div class="row">
                    @foreach (var slika in Model.Slike)
                    {
                        <div class="col-md-4 mb-4 d-flex flex-column align-items-center">
                            <div class="card w-100">
                                <img src="http://localhost:9000/slike/@slika.Putanja"
                                     class="card-img-top img-fluid"
                                     alt="Snimka pregleda"
                                     style="height: 200px; object-fit: cover;">
                                <div class="card-footer text-center">
                                    <form asp-controller="Slike" asp-action="Delete" method="post" style="display: inline">
                                        <input type="hidden" name="id" value="@slika.Id" />
                                        @Html.AntiForgeryToken()
                                        <button type="button"
                                                class="btn btn-danger btn-sm"
                                                onclick="confirmDelete(this)">
                                            <i class="fas fa-trash"></i> Obriši
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            }
            else
            {
                <p class="text-muted">Nema priloženih slika</p>
            }
        </div>
    </div>


    <a asp-action="Index" class="btn btn-secondary mt-4">
        <i class="fas fa-arrow-left"></i> Povratak na listu
    </a>
</div>

MedicinskiSustav/Views/Pregledi/Edit.cshtml
@model MedicinskiSustav.Viewmodels.PregledEditVM

<h2>Uredi pregled</h2>

<form asp-action="Edit">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="PacijentId" />

    <div class="form-group mb-3">
        <label asp-for="SifraPregleda" class="form-label"></label>
        <select asp-for="SifraPregleda" asp-items="Html.GetEnumSelectList<SifraPregleda>()" class="form-select"></select>
        <span asp-validation-for="SifraPregleda" class="text-danger"></span>
    </div>

    <div class="form-group mb-3">
        <label asp-for="VrijemePregleda" class="form-label"></label>
        <input asp-for="VrijemePregleda" class="form-control" />
        <span asp-validation-for="VrijemePregleda" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">
        <i class="fas fa-save"></i> Spremi promjene
    </button>
    <a asp-action="Index" class="btn btn-secondary">
        <i class="fas fa-arrow-left"></i> Natrag
    </a>
</form>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MedicinskiSustav/Views/Pregledi/Index.cshtml
@model IEnumerable<MedicinskiSustav.Viewmodels.PregledVM>

<h2>Popis pregleda</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Pacijent</th>
            <th>Šifra pregleda</th>
            <th>Vrijeme pregleda</th>
            <th>Akcije</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.PacijentImePrezime</td>
                <td>@item.SifraPregleda</td>
                <td>@item.VrijemePregleda.ToString("dd.MM.yyyy HH:mm")</td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info btn-sm">
                        <i class="fas fa-info-circle"></i> Detalji
                    </a>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning btn-sm">
                        <i class="fas fa-edit"></i> Uredi
                    </a>
                    <form asp-action="Delete" method="post" style="display:inline">
                        <input type="hidden" name="id" value="@item.Id" />
                        @Html.AntiForgeryToken()
                        <button type="button" class="btn btn-danger btn-sm" onclick="confirmDelete(this)">
                            <i class="fas fa-trash"></i> Obriši
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>